[package]
name = "devfest"
version = "0.1.1"
description = "devfest python application"
readme = "README.md"
 
[dependencies]
"wasmer/python" = "^3.12.6"
 
[fs]
"/pkg" = "./pkg"
"/cpython/lib/python3.12" = "./.env/lib/python3.11"
 
[[command]]
name = "script"
module = "wasmer/python:python"
runner = "wasi"
 
[command.annotations.wasi]
main-args = [ # This is the command we want the python runner to run
    "main",
]
env = ["PYTHONEXECUTABLE: /bin/python"] # This is the path to the python executable