"""empty message

Revision ID: 197bdc37085b
Revises: 9cfccda58281
Create Date: 2026-03-10 17:12:15.178247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197bdc37085b'
down_revision = '9cfccda58281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pay_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('pay_data')

    # ### end Alembic commands ###
