"""empty message

Revision ID: 9cfccda58281
Revises: 
Create Date: 2026-03-02 13:45:26.857829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cfccda58281'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('adm_id', sa.BigInteger(), nullable=False),
    sa.Column('adm_role', sa.Enum('super', 'manager', name='admin_roles'), nullable=False),
    sa.Column('adm_full_name', sa.String(length=150), nullable=False),
    sa.Column('adm_email', sa.String(length=150), nullable=False),
    sa.Column('adm_password_hash', sa.String(length=255), nullable=False),
    sa.Column('adm_created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('adm_id'),
    sa.UniqueConstraint('adm_email')
    )
    op.create_table('tickets',
    sa.Column('tkt_id', sa.BigInteger(), nullable=False),
    sa.Column('tkt_name', sa.String(length=150), nullable=False),
    sa.Column('tkt_description', sa.Text(), nullable=True),
    sa.Column('tkt_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tkt_created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('tkt_id')
    )
    op.create_table('tracks',
    sa.Column('trk_id', sa.BigInteger(), nullable=False),
    sa.Column('trk_level', sa.Enum('general', 'intermediate', 'advanced', 'junior', name='track_levels'), nullable=False),
    sa.Column('trk_created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('trk_id')
    )
    op.create_table('sessions',
    sa.Column('ses_id', sa.BigInteger(), nullable=False),
    sa.Column('ses_title', sa.String(length=200), nullable=False),
    sa.Column('ses_description', sa.Text(), nullable=True),
    sa.Column('ses_track_id', sa.BigInteger(), nullable=True),
    sa.Column('ses_start_time', sa.DateTime(), nullable=True),
    sa.Column('ses_created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ses_track_id'], ['tracks.trk_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ses_id')
    )
    op.create_table('users',
    sa.Column('usr_id', sa.BigInteger(), nullable=False),
    sa.Column('usr_firstname', sa.String(length=150), nullable=False),
    sa.Column('usr_lastname', sa.String(length=100), nullable=False),
    sa.Column('usr_email', sa.String(length=150), nullable=False),
    sa.Column('usr_password_hash', sa.String(length=255), nullable=False),
    sa.Column('usr_summary', sa.String(length=150), nullable=True),
    sa.Column('usr_image', sa.String(length=150), nullable=True),
    sa.Column('usr_track_id', sa.BigInteger(), nullable=True),
    sa.Column('usr_created_at', sa.DateTime(), nullable=True),
    sa.Column('usr_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usr_track_id'], ['tracks.trk_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('usr_id'),
    sa.UniqueConstraint('usr_email')
    )
    op.create_table('conversations',
    sa.Column('con_id', sa.BigInteger(), nullable=False),
    sa.Column('con_title', sa.String(length=200), nullable=True),
    sa.Column('con_content', sa.Text(), nullable=False),
    sa.Column('con_created_by', sa.BigInteger(), nullable=True),
    sa.Column('con_created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['con_created_by'], ['users.usr_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('con_id')
    )
    op.create_table('orders',
    sa.Column('ord_id', sa.BigInteger(), nullable=False),
    sa.Column('ord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('ord_ticket_id', sa.BigInteger(), nullable=True),
    sa.Column('ord_order_ref', sa.String(length=50), nullable=True),
    sa.Column('ord_total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ord_status', sa.Enum('pending', 'paid', 'cancelled', 'refunded', name='order_status'), nullable=True),
    sa.Column('ord_created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ord_ticket_id'], ['tickets.tkt_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ord_user_id'], ['users.usr_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ord_id'),
    sa.UniqueConstraint('ord_order_ref')
    )
    op.create_table('user_session',
    sa.Column('use_id', sa.Integer(), nullable=False),
    sa.Column('use_userid', sa.BigInteger(), nullable=False),
    sa.Column('use_sessionid', sa.BigInteger(), nullable=False),
    sa.Column('use_datereg', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['use_sessionid'], ['sessions.ses_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['use_userid'], ['users.usr_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('use_id')
    )
    op.create_table('conversation_messages',
    sa.Column('msg_id', sa.BigInteger(), nullable=False),
    sa.Column('msg_conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('msg_user_id', sa.BigInteger(), nullable=True),
    sa.Column('msg_message', sa.Text(), nullable=False),
    sa.Column('msg_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['msg_conversation_id'], ['conversations.con_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['msg_user_id'], ['users.usr_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('msg_id')
    )
    op.create_table('payment',
    sa.Column('pay_id', sa.BigInteger(), nullable=False),
    sa.Column('pay_order_id', sa.BigInteger(), nullable=False),
    sa.Column('pay_payment_ref', sa.String(length=100), nullable=True),
    sa.Column('pay_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pay_status', sa.Enum('pending', 'successful', 'failed', name='payment_status'), nullable=False),
    sa.Column('pay_paid_at', sa.DateTime(), nullable=True),
    sa.Column('pay_created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pay_order_id'], ['orders.ord_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pay_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('conversation_messages')
    op.drop_table('user_session')
    op.drop_table('orders')
    op.drop_table('conversations')
    op.drop_table('users')
    op.drop_table('sessions')
    op.drop_table('tracks')
    op.drop_table('tickets')
    op.drop_table('admins')
    # ### end Alembic commands ###
